### ISSUE TITLE
Flip webcam horizontally/vertically not working

### ISSUE THREAD

**Issue by JoostdeK** [poulou0/OctoPrint-WebcamExtras#1]
Hi,

i just installed this addon and it works fine. Always wanted to ability to zoom in a bit more :). The issue I'm having is that it ignores the settings I provided in the Webcam&Timelapse options. I have flip horizontally and vertically toggled, but when I zoom it reverts back to the standard settings. Not in the settings, but in the visible video. After zooming in the video stays flipped. Refreshing the page resets it back to normal.

EDIT: added image of the options I'm using

![image](https://user-images.githubusercontent.com/110180328/233949411-dee8df91-cb0a-4e47-8ee1-8ffd25117226.png)

**Comment by Letme** [comment]
I have exact same problem. When I zoom the flip screen settings are not respected. (I use 4:3 stream aspect ratio, but issue is the same).

**Comment by poulou0** [comment]
Hello and thank you for reporting the first issue :1st_place_medal: 
I pushed an update to hopefully fix it.

You can force check update from Settings > OctoPrint >Software Update.
![image](https://user-images.githubusercontent.com/48758557/233974244-e5001a40-0449-4514-aa0f-6c1412abb1f4.png)

**Comment by JoostdeK** [comment]
Awesome, thanks for the quick fix!

**Comment by poulou0** [comment]
No problem, I'm trying to boost my github, a star if you like the plugin will be really appreciated ⭐😇
