### ISSUE TITLE
UI Customizer plugin support

### ISSUE THREAD

**Issue by FireflyJar** [poulou0/OctoPrint-WebcamExtras#2]
Installed using OctoPrint Plugin manager, rebooted and verified it is on.
Issue: I do not have an icon to zoom in webcam.
OctoPrint 1.8.7 ,  I am using UI Customizer: 0.1.9.4 

update:  turned off UI Customizer and now I see icon.

**Comment by poulou0** [comment]
Zooming should work out of the box with UI customizer.

But to see the buttons you should disable this option 👍
![image](https://user-images.githubusercontent.com/48758557/234091188-d97ee367-65e5-4c7d-839e-90261417b22f.png)

**Comment by FireflyJar** [comment]
Thank you!  that worked

**Comment by poulou0** [comment]
No problem, I'm trying to boost my github, a star if you like the plugin will be really appreciated ⭐😇
