### ISSUE TITLE
Dashboard plugin support

### ISSUE THREAD

**Issue by nicktodorov** [poulou0/OctoPrint-WebcamExtras#3]
When using Dashboard plugin and showing the camera there, the controls buttons are not visible.
It works with Control tab, it works with UI customizer webcam section, but not in the Dashboard stream.

**Comment by poulou0** [comment]
Thank you for reporting it.
I will add it to the "known issues" and in my to-do list to play around and see what can I do.

_Note to self: We are talking about the `OctoPrint-Dashboard` and the `WebCam view`  widget
https://plugins.octoprint.org/plugins/dashboard/_

**Comment by nicktodorov** [comment]
Yes, this Dashboard plugin and that widget.

**Comment by TheDukeSr** [comment]
+1
Same problem here, so it's definitely the Dashboard plugin that gives a conflict.

**Comment by poulou0** [comment]
Hey @TheDukeSr and @nicktodorov 
I just released a new version to support the Dashboard plugin

let me know if it works for you and I will open the issue again.

PS. Please consider leaving a star on the repo ⭐
