### ISSUE TITLE
Maximizing on a super ultra wide monitor cuts off top/bottom of image

### ISSUE THREAD

**Issue by seanmcne** [poulou0/OctoPrint-WebcamExtras#5]
Hi, when maximizing the webcam on a super ultrawide it respects the width of the screen but not the height so it gets stretched and cropped. 

Would it be possible to (either one of both)
- Determine if width or height is the limiting factor and scale as appropriate to avoid cropping
- Have a screen-fill mode where it will maximize but only within the confines of the browser viewport

Thanks!

**Comment by poulou0** [comment]
Hey! Seemed pretty straight forward so I pushed an update to hopefully fix it.

Let me know. :)

You can force update from Settings > OctoPrint > Software Update.
![image](https://user-images.githubusercontent.com/48758557/234710767-4c5520c0-f5e6-4f9f-a4fd-dd1e1d8f3670.png)
