### ISSUE TITLE
Issue with TouchUI

### ISSUE THREAD

**Issue by ryancasler** [poulou0/OctoPrint-WebcamExtras#6]
The Plugin Causes an issue when using TouchUI Plugin.  It causes the main system menu to not show up at all and causes the other pages to not render in the correct width on touch (mobile)  devices.  Is there anyway it could just be disabled when TouchUI is enabled?  Love the plugin but have to disable it unless I can choose on which clients it should load.  It would also be okay if this were a per-client setting that was stored in a cookie or something.

**Comment by poulou0** [comment]
Hello! Thank you for the feedback and the suggestions!
It was a one-liner to disable my changes when the TouchUI is active.
Hope this fixes it, let me know. :)
https://github.com/poulou0/OctoPrint-WebcamExtras/releases/tag/0.0.10

You can force update from Settings > OctoPrint > Software Update.
![234710767-4c5520c0-f5e6-4f9f-a4fd-dd1e1d8f3670](https://user-images.githubusercontent.com/48758557/235421692-3d2d5319-5e27-4fd9-a300-02eb3edac52d.png)

PS. I'm trying to boost my github, a star if you like the plugin will be really appreciated ⭐

**Comment by ryancasler** [comment]
That worked perfectly!   Thank so much for such a quick response.
