### ISSUE TITLE
Flip webcam horizontally/vertically not working

### ISSUE THREAD

**Issue by djepsylon** [poulou0/OctoPrint-WebcamExtras#7]
camera inverse 
i ve put my cam with the horizontal flip of the video and with your plugin it put the picture without this setting this is strange
it result of my video head in the bottom

**Comment by poulou0** [comment]
Hmm I thought i fixed that last week, can you make sure you are using the latest version 0.0.10?
https://github.com/poulou0/OctoPrint-WebcamExtras/issues/1#issuecomment-1519889758

**Comment by djepsylon** [comment]
o,k thank you, with the latest version it's fixed

**Comment by poulou0** [comment]
Great!!

Btw if you are using it, a star in github will be appreciated ⭐
(I try to reach the 16 stars to get the achievement)
