### ISSUE TITLE
Does this plugin work on the latest camera-streamer based webcam stack build (20230328122604)

### ISSUE THREAD

**Issue by b-morgan** [poulou0/OctoPrint-WebcamExtras#8]
I have an RPi 4B (4GB) with an RPi camera V3. This camera is not supported (very well) on the current OctoPi 1.0.0 release but works perfectly using the OctoPi image referenced [here](https://github.com/OctoPrint/OctoPi-UpToDate/issues/3). I expect this camera-streamer, libcamera based stack will soon replace the stack in the current OctoPi 1.0.0 release.

**Comment by poulou0** [comment]
The plugin operates only in the front-end with javascript.
If nothing changes in the DOM i have faith that it will work. 👍

Did you find any problem? I have a spare RPi, maybe i can find a camV3 and try to reproduce it.

**Comment by b-morgan** [comment]
I didn't try it. I don't currently have a physical printer attached to that RPi. My printer is attached to an RPi 3B (with an RPi camera V2) running OctoPi 0.18.0 with OctoPrint 1.8.7.

If you want me to try the plugin on my RPi 4B, let me know. Otherwise, I'll let you do the testing. BTW, I'm guessing that any camera will work as its the changes to the stack that needs to be verified.

**Comment by poulou0** [comment]
Any help is welcome of course. I believe it will work for the exact reason that you said :))
If you find any problem let me know and I'll be happy to re-open the issue.
